language: node_js
node_js:
    - 10
cache:
    - yarn
before_install:
    - yarn config set registry https://registry.npm.taobao.org
    - bash mkdir.sh
install:
    - yarn install
script:
    - node generateMD.js
    - yarn build
after_success:
    - git config --global user.name "hellottxo"
    - git config --global user.email "654720416@qq.com"
    - git add .
    - cd docs/.vuepress/dist
    - git init
    - git checkout docs
    - git add .
    - git commit -m 'deploy'
    - git push --force "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages
env:
  global:
    - GH_REF: github.com/Hellottxo/leetcode-records.git
